### ISSUE TITLE
Conversion error

### ISSUE THREAD

**Issue by lcottereau** [mmistakes/skinny-bones-jekyll#21]
Hello,
I am trying to run this theme in order to use it for my site. After downloading and running `bundle install`, I tried `bundle exec jekyll build` but had the following errors : 

    Generating... 
    Conversion error: Jekyll::Converters::Scss encountered an error converting 'css/main.scss'.
    Conversion error: Invalid CSS after " webkit-image": expected ")", was ": -webkit- + $p..."
    jekyll 2.4.0 | Error:  Invalid CSS after "      webkit-image": expected ")", was ": -webkit- + $p..."

I have tried many combinations of bundle install/update, setting specific versions of jekyll or jekyll-sass-converters but it doesn't seem to work. Here is an exemple of a configuration that doesn't work

```
(...)/skinny-bones-jekyll-master$ bundle update
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using blankslate 2.1.2.4
Using sass 3.4.12
Using thor 0.19.1
Using bourbon 4.2.0
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using fast-stemmer 1.0.2
Using classifier-reborn 2.0.3
Using coffee-script-source 1.9.1
Using execjs 2.3.0
Using coffee-script 2.3.0
Using colorator 0.1
Using ffi 1.9.6
Using jekyll-coffeescript 1.0.1
Using jekyll-gist 1.1.0
Using jekyll-paginate 1.1.0
Using jekyll-sass-converter 1.3.0
Using rb-fsevent 0.9.4
Using rb-inotify 0.9.5
Using listen 2.8.5
Using jekyll-watch 1.2.1
Using kramdown 1.5.0
Using liquid 2.6.2
Using mercenary 0.3.5
Using posix-spawn 0.3.10
Using yajl-ruby 1.2.1
Using pygments.rb 0.6.2
Using redcarpet 3.2.2
Using safe_yaml 1.0.4
Using parslet 1.5.0
Using toml 0.1.2
Using jekyll 2.4.0
Using jekyll-sitemap 0.6.3
Using neat 1.7.1
Using octopress-deploy 1.1.0
Using octopress-hooks 2.6.0
Using octopress-escape-code 2.0.6
Using titlecase 0.1.1
Using octopress 3.0.0.rc.33
Using bundler 1.8.2
Bundle updated!
```

Any idea ? Thank you for looking at my problem.

**Comment by mmistakes** [comment]
Looks to me it's [something with Bourbon](https://github.com/mmistakes/skinny-bones-jekyll/search?utf8=%E2%9C%93&q=webkit-image) and one its Sass partials. I did a search for `webkit-image` in the `_sass` folder to find where it was referenced and it's definitely a Bourbon file.

I know that gem recently was updated to support Libsass, it's possible it broke something with regards to how Jekyll processes Sass files. That or there's a conflict with another gem. I would try and roll back to the [exact gem versions](https://github.com/mmistakes/skinny-bones-jekyll/blob/master/Gemfile.lock) I bundled with the theme because it works fine for me on a Mac OS X setup and Windows 7.

You could also try updating the Bourbon partials by [following these instructions](https://github.com/thoughtbot/bourbon/wiki/Command-Line-Interface#update).

Other than those I don't have any more suggestions.

**Comment by lcottereau** [comment]
Thank you so much for your quick and very detailled answer. 

I have uninstalled ruby and reinstalled and it now works. I am not sure what happended, maybe I had installed gems as `sudo` with `bundle` ? Anyway thank you for pointing me in the right direction.
