### ISSUE TITLE
Mobile Homepage Image & jekyll build/serve

### ISSUE THREAD

**Issue by aznspy256** [mmistakes/skinny-bones-jekyll#27]
My site is www.nolanhu.com
For some reason in the mobile version, the main image doesn't shrink itself. I only see a part of the image instead of the whole image.

Also, I have to run "bundle exec jekyll build" & "bundle exec jekyll serve" everytime for it to work. What's the solution to that issue?

**Comment by mmistakes** [comment]
The way I currently have it setup on the demo was a quick hack to display the lead image full width. I purposely didn't include it in the theme or document it anywhere because it's not really ready for prime time use.

To get it to scale how you want, you'll need to play around with the CSS. I'd suggest [starting here](https://css-tricks.com/perfect-full-page-background-image/) to get some inspiration on how you can do that.

As for `bundle exec jekyll build` and `serve`, I don't know any way around that. It comes down to the  gems I'm bundling with the Skinny Bones and various conflicts they may have with each other. By running `bundle exec` you're essentially saying "hey load the specific gems set in my `Gemfile`. It really depends on what versions you have installed, if there are any conflicts, and what your system is (Mac OS X, Linux, Windows, etc).

For example, I have no problem running a vanilla `jekyll serve` on my Mac, but on Windows I always have to use `bundle exec`. Your mileage may vary and by using `bundle exec` you eliminate a lot of the problems.

I've heard from some that nuking `Gemfile` and `Gemfile.lock` let them drop `bundle exec`, but I wouldn't suggest that since it becomes a pain to manage gem dependencies in the future.

If you want more background on all this bump around the closed issues here and on my other theme repos. About once a week this question comes up...
