### ISSUE TITLE
Text-wrapped images

### ISSUE THREAD

**Issue by michaellevy** [mmistakes/skinny-bones-jekyll#46]
Hi Michael, thanks for this; it's awesome. One thing I often want to do is wrap text around a partial-width image. I don't see a demo-ed way to do this, so I've been doing something like this: 

```
<img align="left" style="width:35%;height:35%;margin:20px 30px" ... >
``` 
Using a relative size, images get too small on mobile, but with an absolute width they get too big and align weird. Is there a better way to do this? Thanks much.

**Comment by mmistakes** [comment]
The better way to do it would be to create a class you can apply to images you'd like to float and have text wrap around.

In the [_helpers.scss](https://github.com/mmistakes/skinny-bones-jekyll/blob/master/_sass/_helpers.scss#L73) file I have a class for floating images to the right. You could take that and adapt for a left aligned image. What my styling does is float the image to the right for wide screens and anything small it doesn't float or wrap at all. 

With some media queries you could assign different widths/heights for your images or do whatever else you want.

Then instead of adding the inline styles to an image you do something like `<img src="image.jpg" class="img-left" alt="">`.

Hope this helps.

**Comment by dixonge** [comment]
Michael, you just solved a big headache for me! I basically duplicated the .image-right section, changed the float and margin and name of the class to reference left, and then added this after an image

`{: .image-left }`

worked like a charm!

**Comment by mmistakes** [comment]
@dixonge :smile:

**Comment by michaellevy** [comment]
Like a charm. Thanks!
