### ISSUE TITLE
Navigation disappears on small screens

### ISSUE THREAD

**Issue by troygilbert** [mmistakes/skinny-bones-jekyll#5]
The top-menu navigation items are hidden on small screens (mobile phone width). This appears to be design and part of the responsive setup, but for the life of me, I cannot find the SASS logic that applies the media queries to do it.

I'd like to have the navigation present at all times (in place of the sliding navigation).

**Comment by mmistakes** [comment]
I recently switched over to using two Jekyll config files: one for production and the other for local development. `_config.yml` has all my production settings and `_config-dev.yml` my development settings.

Basically the only difference between the two is one has `url: https://mydomain.com` and the other  `url: http://localhost:4000`

When I'm working locally I fire up Jekyll like so and it uses the dev config file so local assets (CSS, JS, images, etc are loaded instead of pulling from the live site). Easy peasy.

```
jekyll serve --config _config-dev.yml
```
