### ISSUE TITLE
Post Grid Impagination with post limit

### ISSUE THREAD

**Issue by Xabacadabra** [mmistakes/skinny-bones-jekyll#54]
Hi! first of all i would like to thank you for this amazing template! (oh, and sorry for my poor english)

I was trying some stuff with the <code>{% include post-grid.html %}</code> function, and i found out that with the post limit paramater set to 4 the impagination get stuck with a maxium three column layout for row

Example:

<code>
  {% for post in site.posts limit:4 %}
    {% include post-grid.html %}
  {% endfor %}
</code>

in the homepage -> http://xabacadabra.github.io/ you'll see that after the third column, the fourth directly start a new line down even if there isn't lack of space

**Comment by mmistakes** [comment]
Something with the `h2.post-title` element is causing the tiles below to not fit the container. If you move the `h2` that is currently inside of `<div class="tiles"></div>` outside of it and place it before that `div` the 4 tiles will fit instead of breaking at the 3rd one.

![screen shot 2016-01-03 at 9 08 25 pm](https://cloud.githubusercontent.com/assets/1376749/12082295/71805476-b25e-11e5-8a77-af94afacb98a.png)

![screen shot 2016-01-03 at 9 08 36 pm](https://cloud.githubusercontent.com/assets/1376749/12082296/75aa25ae-b25e-11e5-80eb-afd7bd977a23.png)

**Comment by Xabacadabra** [comment]
thank you very much!!
