### ISSUE TITLE
How to delete the right panel?

### ISSUE THREAD

**Issue by Nowosad** [mmistakes/skinny-bones-jekyll#58]
Is there any way to delete left panel in Skinny Bones?

**Comment by mmistakes** [comment]
Left panel? Do you mean the right sidebar?

**Comment by Nowosad** [comment]
Yes, of course - the right sidebar;)

**Comment by mmistakes** [comment]
If you look at the various `_layouts` just remove the ad sidebar, which is this line:

```html
{% if page.ads == true %}<div class="ads">{% include advertising.html %}</div><!-- /.ads -->{% endif %}
```

You'll probably have to mess with the CSS too for `#main .inner-wrap` since its not set to be 100% to account for the sidebar. Rip out [these lines](https://github.com/mmistakes/skinny-bones-jekyll/blob/master/_sass/_layout.scss#L147-L149) in `_layout.scss` and possibly replace with `width: 100%` and you should be all set.

```scss
#main {
	.inner-wrap {
		@include media($medium) {
			@include span-columns(9);
		}
	}
}
```

**Comment by Nowosad** [comment]
Thanks for the answer and also for your great work!
